version: '3'

services:
  airmock:
    image: airmock
    container_name: airmock
    ports:
    - "10000:10000"
    env_file:
    - airmock.common.env
    - airmock.specific.env
    labels:
      org.labels-schema.group: "airmock"
